spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres_db
    username: pguser
    password: pguser
    driverClassName: org.postgresql.Driver

  jpa:
    database: postgresdb
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    loadbalancer:
      ribbon:
        enable: true

  flyway:
    locations:
      classpath: db/migration
